### ISSUE TITLE
Add kotlin support

### ISSUE THREAD

**Issue by rkmax** [kmmraj/androidcleancode-generator#1]

**Comment by kmmraj** [comment]
Refer [here](https://github.com/kmmraj/KotlinCleanCode4Android) and [here](https://github.com/kmmraj/kt-clean-code4Android-generator).
Refer to posts [here](https://medium.com/@kmmraj/kotlin-clean-code-for-android-series-f3b32307342d)

**Comment by rkmax** [comment]
thanks @kmmraj
